import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './Navbar'
import AuthProvider from './api/auth/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <script async src='https"//www.googletagmanager.com/gtag/js?id' />
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() {dataLayer.push(arguments); }
        gtag('js', new Date());
        gtag('config', 'G-XXXXXXXXXX'); // Replace with your GA tracking ID
      </script> */}

      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          <main className='p-5'>{children}</main>
        </AuthProvider>
      </body>
    </html>
  )
}
